# Generated by Django 3.2.13 on 2022-07-04 09:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopapp', '0006_auto_20220704_0840'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='stars',
            new_name='thumbs_up',
        ),
    ]
