# Generated by Django 3.2.13 on 2022-07-08 10:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopapp', '0007_rename_stars_comment_thumbs_up'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='collection',
            options={'ordering': ('name',)},
        ),
    ]
