# Generated by Django 3.2.13 on 2022-07-10 02:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopapp', '0012_auto_20220710_0145'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='collection',
        ),
        migrations.DeleteModel(
            name='Collection',
        ),
    ]
