# Generated by Django 3.2.13 on 2022-07-10 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopapp', '0014_customer_device'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='ordered_on',
            new_name='date_ordered',
        ),
        migrations.AddField(
            model_name='order',
            name='transaction_id',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
