# Generated by Django 3.2.13 on 2022-07-10 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopapp', '0015_auto_20220710_0701'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='details',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
